#ifndef __ExploreFrame__
#define __ExploreFrame__

/**
@file
Subclass of BaseExploreFrame, which is generated by wxFormBuilder.
*/

#include "HLMWADFrames.h"

//// end generated include

#include "WADArchive.h"
#include <wx/sharedptr.h>

/** Implementing BaseExploreFrame */
class ExploreFrame : public BaseExploreFrame
{
	protected:
		// Handlers for BaseExploreFrame events.
		void OnOpenClicked( wxCommandEvent& event );
		void OnSaveClicked( wxCommandEvent& event );
		void OnSaveAsClicked( wxCommandEvent& event );
		void OnExtractClicked( wxCommandEvent& event );
		void OnQuitClicked( wxCommandEvent& event );
		void OnFileListSelectionChanged( wxDataViewEvent& event );
		void OnFileListDoubleClick( wxMouseEvent& event );
	public:
		/** Constructor */
		ExploreFrame( wxWindow* parent );
	//// end generated class members

	private:
		wxSharedPtr<WADArchive> m_archive;

		void OpenFile(const wxString& filename);

};

#endif // __ExploreFrame__
