/*
 ** HLMWadExplorer
 **
 ** Copyright (C) 2015 Tobias Taschner <github@tc84.de>
 **
 ** Licensed under GPL v3 or later
 */
#ifndef __ExploreFrame__
#define __ExploreFrame__

/**
@file
Subclass of BaseExploreFrame, which is generated by wxFormBuilder.
*/

#include "HLMWADFrames.h"

//// end generated include

#include "WADArchive.h"
#include <wx/sharedptr.h>
#include <wx/filehistory.h>
#include <set>

class HexView;

/** Implementing BaseExploreFrame */
class ExploreFrame : public BaseExploreFrame
{
	protected:
		// Handlers for BaseExploreFrame events.
		void OnWindowClose( wxCloseEvent& event );
		void OnOpenClicked( wxCommandEvent& event );
		void OnSaveClicked( wxCommandEvent& event );
		void OnSaveAsClicked( wxCommandEvent& event );
		void OnMergeClicked( wxCommandEvent& event );
		void OnSwitchBaseWadClicked(wxCommandEvent& event);
		void OnExtractClicked( wxCommandEvent& event );
		void OnReplaceClicked( wxCommandEvent& event );
		void OnAddClicked( wxCommandEvent& event );
		void OnDeleteClicked( wxCommandEvent& event );
		void OnQuitClicked( wxCommandEvent& event );
		void OnAboutClicked( wxCommandEvent& event );
		void OnSearchCtrlButton(wxCommandEvent& event);
		void OnSearchCtrlText(wxCommandEvent& event);
		void OnSearchCtrlEnter(wxCommandEvent& event);
		void OnSearchTimer(wxTimerEvent& event);
		void OnFileListSelectionChanged(wxDataViewEvent& event);
		void OnFileListDoubleClick( wxMouseEvent& event );
		void OnRecentFileClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		ExploreFrame( wxWindow* parent );
	//// end generated class members
		~ExploreFrame();

		bool OpenBaseFile(bool forceSelection = false);

	private:
		friend class FileDataModel;

		wxSharedPtr<WADArchive> m_archive;
		wxString m_patchFileName;
		wxFileHistory m_fileHistory;
		bool m_ignoreSearch;
		HexView* m_hexView;
	
		const WADArchiveEntry* GetSelectedEntry() const;

		void OpenFile(const wxString& filename);

		void UpdateTitle();
	
		wxString GetGameBasePath() const;
	
		wxString GetModPath() const;

		void SelectItem(WADDirEntry* entry);

		void ApplyFilter(const wxString& filter);

		bool CreatePatch();

		void ExtractPak(const WADArchiveEntry* entry);
};

#endif // __ExploreFrame__
