#ifndef __StringTablePanel__
#define __StringTablePanel__

/**
@file
Subclass of BaseStringTablePanel, which is generated by wxFormBuilder.
*/

#include "HLMWADFrames.h"

//// end generated include

/** Implementing BaseStringTablePanel */
class StringTablePanel : public BaseStringTablePanel
{
	public:
		/** Constructor */
		StringTablePanel( wxWindow* parent );
	//// end generated class members
	
		void LoadStringTable(const void* data, size_t dataSize);
};

#endif // __StringTablePanel__
