#ifndef __TexturePackPanel__
#define __TexturePackPanel__

/**
@file
Subclass of BaseTexturePackPanel, which is generated by wxFormBuilder.
*/

#include "HLMWADFrames.h"

//// end generated include

#include "TexturePack.h"
#include <wx/graphics.h>

/** Implementing BaseTexturePackPanel */
class TexturePackPanel : public BaseTexturePackPanel
{
	protected:
		// Handlers for BaseTexturePackPanel events.
		void OnTextureListBoxSelected( wxCommandEvent& event );
		void OnFrameSpinCtrlChanged( wxSpinEvent& event );
		void OnFrameSpinCtrlEnterPressed( wxCommandEvent& event );
	public:
		/** Constructor */
		TexturePackPanel( wxWindow* parent );
	//// end generated class members
	
		void LoadTexture(wxInputStream& iStr, wxBitmap bitmap);

	private:
		wxBitmap m_bitmap;
		wxGraphicsBitmap m_drawBitmap;
		wxSharedPtr<TexturePack> m_texturePack;
};

#endif // __TexturePackPanel__
